package msa.commons.event;

public enum EventId {
    /* MICROSERVICIO DE TIPO USUARIO */
    VALIDATE_TYPE_USER,
    /* MICROSERVICIO DE USUARIO */
    CREATE_USER,
    FAILED_USER,
    /* MICROSERVICIO DE COUNTRY */
    GET_COUNTRY_BY_ID,
    GET_COUNTRY_BY_NAME,
    /* MICROSERVICIO DE RESERVA DE HOTEL */
    CREATE_BOOKING,
    FAILED_BOOKING,
    VALIDATE_CUSTOMER_AND_ROOMS,
    /* MICROSERVICIO DE HABITACIONES DE HOTEL */
    GET_ROOM,
    /* MICROSERVICIO DE Aeronave */
    AIRCRAFT_VALIDATE_CAPACITY,
    /* MICROSERVICIO DE Aeropuerto */
    GET_AIRPORT_BY_ID,
    /* MICROSERVICIO DE Vuelo */
    EXIST_FLIGHT_INSTANCE,
    FLIGHT_INSTANCE_FOUND,
    FLIGHT_INSTANCE_NOT_FOUND,
    /* MICROSERVICIO DE Cliente Aerolinea */
    CUSTOMER_AIRLINE_INIT_VALIDATE_FLIGHT,
    CUSTOMER_AIRLINE_COMMIT_SAGA,
    CUSTOMER_AIRLINE_ROLLBACK_SAGA,
    /* MICROSERVICIO DE Reserva Aerolinea */
    RESERVATION_AIRLINE_INIT_CREATE_CUSTOMER,
}
