package msa.commons.event;

public enum EventId {
    /* MICROSERVICIO DE TIPO USUARIO */
    VALIDATE_TYPE_USER,
    BEGIN_CREATE_USER,
    /* MICROSERVICIO DE USUARIO */
    CREATE_USER,
    FAILED_USER,
    /* MICROSERVICIO DE COUNTRY */
    GET_COUNTRY_BY_ID,
    GET_COUNTRY_BY_NAME,
}
